import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/header/header';
import { Cormorant_Garamond, Roboto } from 'next/font/google';

const cormorantGaramondFont = Cormorant_Garamond({
  weight: '400',
  variable: '--cormorant-garamond-font',
});
const robotoFont = Roboto({
  weight: '400',
  variable: '--roboto-font',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${robotoFont.variable} ${cormorantGaramondFont.variable}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
